services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prueba_tecnica_fixlat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prueba_tecnica_fixlat"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/prueba_tecnica_fixlat?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-pHB9kcH5tE9ItHceBcB4nbKpypn4GJmnBQ2QpzFZMjs}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
    ports:
      - "3000:3000"

volumes:
  postgres_data: